2021-10-17 21:28:00,364 INFO    MainThread:370931 [wandb_setup.py:_flush():69] setting env: {}
2021-10-17 21:28:00,364 INFO    MainThread:370931 [wandb_setup.py:_flush():69] setting login settings: {}
2021-10-17 21:28:00,364 INFO    MainThread:370931 [wandb_init.py:_log_setup():342] Logging user logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/NLP/NLP-with-Disaster-Tweets/wandb/run-20211017_212800-250jsf6a/logs/debug.log
2021-10-17 21:28:00,364 INFO    MainThread:370931 [wandb_init.py:_log_setup():343] Logging internal logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/NLP/NLP-with-Disaster-Tweets/wandb/run-20211017_212800-250jsf6a/logs/debug-internal.log
2021-10-17 21:28:00,365 INFO    MainThread:370931 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fb6b44ba610>
2021-10-17 21:28:00,365 INFO    MainThread:370931 [wandb_init.py:init():375] calling init triggers
2021-10-17 21:28:00,365 INFO    MainThread:370931 [wandb_init.py:init():382] wandb.init called with sweep_config: {}
config: {}
2021-10-17 21:28:00,365 INFO    MainThread:370931 [wandb_init.py:init():424] starting backend
2021-10-17 21:28:00,366 INFO    MainThread:370931 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-10-17 21:28:00,421 INFO    MainThread:370931 [backend.py:ensure_launched():135] starting backend process...
2021-10-17 21:28:00,474 INFO    MainThread:370931 [backend.py:ensure_launched():140] started backend process with pid: 371831
2021-10-17 21:28:00,475 INFO    MainThread:370931 [wandb_init.py:init():429] backend started and connected
2021-10-17 21:28:00,628 INFO    MainThread:370931 [wandb_run.py:_label_probe_notebook():815] probe notebook
2021-10-17 21:28:00,629 INFO    MainThread:370931 [wandb_init.py:init():477] updated telemetry
2021-10-17 21:28:00,629 INFO    MainThread:370931 [wandb_init.py:init():500] communicating current version
2021-10-17 21:28:01,523 INFO    MainThread:370931 [wandb_init.py:init():505] got version response upgrade_message: "wandb version 0.12.4 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-10-17 21:28:01,524 INFO    MainThread:370931 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-10-17 21:28:02,044 INFO    MainThread:370931 [wandb_init.py:init():540] starting run threads in backend
2021-10-17 21:28:07,051 INFO    MainThread:370931 [wandb_run.py:_console_start():1601] atexit reg
2021-10-17 21:28:07,051 INFO    MainThread:370931 [wandb_run.py:_redirect():1475] redirect: SettingsConsole.WRAP
2021-10-17 21:28:07,051 INFO    MainThread:370931 [wandb_run.py:_redirect():1512] Wrapping output streams.
2021-10-17 21:28:07,052 INFO    MainThread:370931 [wandb_run.py:_redirect():1536] Redirects installed.
2021-10-17 21:28:07,052 INFO    MainThread:370931 [wandb_init.py:init():565] run started, returning control to user process
2021-10-17 21:28:07,169 INFO    MainThread:370931 [wandb_init.py:_pause_backend():256] pausing backend
2021-10-17 21:28:07,169 INFO    MainThread:370931 [jupyter.py:save_ipynb():301] looking for notebook: 00.ipynb
2021-10-17 21:28:07,724 INFO    MainThread:370931 [wandb_init.py:_pause_backend():260] saved code: <wandb.sdk.wandb_artifacts.Artifact object at 0x7fb80801ce50>
2021-10-17 21:28:11,925 INFO    MainThread:370931 [wandb_init.py:_resume_backend():265] resuming backend
2021-10-17 21:28:11,931 INFO    MainThread:370931 [wandb_setup.py:_flush():69] setting env: {}
2021-10-17 21:28:11,932 INFO    MainThread:370931 [wandb_setup.py:_flush():69] setting login settings: {}
2021-10-17 21:28:11,932 INFO    MainThread:370931 [wandb_init.py:_log_setup():342] Logging user logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/NLP/NLP-with-Disaster-Tweets/wandb/run-20211017_212811-5t8odtbr/logs/debug.log
2021-10-17 21:28:11,932 INFO    MainThread:370931 [wandb_init.py:_log_setup():343] Logging internal logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/NLP/NLP-with-Disaster-Tweets/wandb/run-20211017_212811-5t8odtbr/logs/debug-internal.log
2021-10-17 21:28:11,932 INFO    MainThread:370931 [wandb_init.py:init():375] calling init triggers
2021-10-17 21:28:11,932 INFO    MainThread:370931 [wandb_init.py:init():382] wandb.init called with sweep_config: {}
config: {}
2021-10-17 21:28:11,932 INFO    MainThread:370931 [wandb_init.py:init():397] re-initializing run, found existing run on stack: 250jsf6a
2021-10-17 21:28:11,933 INFO    MainThread:370931 [wandb_run.py:finish():1271] finishing run ranuga-d/kickstarter-NLP-V4/250jsf6a
